E2E Testing Integration
Cybrid-app/cybrid-sdk-android pull request #56
Opened 2022-07-14 16:47 UTC by nalancer08

### Type of change

- [ ] Chore
- [X] Feature
- [ ] Bug fix

### Linked issue

- [X] Not tracked

### Why
Test DemoApp and include to Firebase TestLab CI and E2E testing with Android UI and Unit Test over DemoApp

2022-07-19 18:42 UTC, jc-cybrid requested changes
Remove commented code

2022-07-19 18:42 UTC, jc-cybrid commented on app/src/androidTest/java/app/cybrid/demoapp/ui/tradeFlow/TradeFlowActivityTest.kt
> +        //.sleep(3000)
Any reason to leave this commented code?

2022-07-19 18:42 UTC, jc-cybrid commented on app/src/main/java/app/cybrid/demoapp/ui/listComponents/entity/Component.kt
> +            //components.add(pricesComponents)
Remove comment.

2022-07-19 18:42 UTC, jc-cybrid commented on app/src/main/java/app/cybrid/demoapp/ui/listComponents/entity/Component.kt
> +            //components.add(pricesAssetsComponents)
Remove comment.

2022-07-19 18:53 UTC, jc-cybrid approved these changes

2022-07-20 17:36 UTC, brent-cybrid approved these changes

2022-07-20 19:41 UTC, nalancer08 commented on app/build.gradle
> +    //androidTestImplementation 'androidx.test:core-ktx:1.8.0'
Yes!

2022-07-20 21:27 UTC, merged